<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1568258417366" stop="1568258417428">
  <name>test_login1</name>
  <labels/>
  <test-cases>
    <test-case start="1568258417366" status="passed" stop="1568258417390">
      <name>Test01.test001</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="32904-MainThread"/>
        <label name="host" value="DESKTOP-ENOEK5R"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1568258417391" status="passed" stop="1568258417393">
      <name>Test01.test002</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="32904-MainThread"/>
        <label name="host" value="DESKTOP-ENOEK5R"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1568258417394" status="failed" stop="1568258417428">
      <name>Test01.test003</name>
      <failure>
        <message>AssertionError: assert 0</message>
        <stack-trace>self = &lt;test_login1.Test01 object at 0x03A5E050&gt;

    def test003(self):
        print("test003被执行")
&gt;       assert 0
E       assert 0

scripts\test_login1.py:14: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="32904-MainThread"/>
        <label name="host" value="DESKTOP-ENOEK5R"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
